name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sbt-test:
    strategy:
      matrix:
        java-version: ['8', '11', '21']
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: 'Set up JDK ${{ matrix.java-version }}'
      uses: actions/setup-java@v4
      with:
        java-version: '${{ matrix.java-version }}'
        distribution: 'adopt'
    - name: 'Setup sbt launcher'
      uses: sbt/setup-sbt@v1
    - name: 'Run tests with JDK ${{ matrix.java-version }}'
      run: sbt test
